### ISSUE TITLE
Announce Client Address?

### ISSUE THREAD

**Issue by dennisai** [ozkatz/django-announce#1]
In your documentation you have:

ANNOUNCE_CLIENT_ADDR - defaults to 'localhost:5500'. should probably be changed for production.

What should this be changed to for production?

**Comment by ozkatz** [comment]
Ok so I'm guessing the docs were not clear enough on this one. The node.js server running announce.js should be externally available on the internet. this setting should point to the fully qualified domain name where announce is running.

for example, if your django site is running at `example.com` and announce.js is running at `announce.example.com` - this setting needs to contain `announce.example.com`.

Please be aware, though, that `ANNOUNCE_CLIENT_ADDR` should be available to the clients over the internet, while the internal API interface (a.k.a `ANNOUNCE_API_ADDR`) is used only between your django app and the node.js server, and **should never be available over the internet or a public network**. use only internal IPs or hostnames for that one.

I hope this answers your question. I will update the docs soon to better reflect this information.

**Comment by dennisai** [comment]
Thanks, this is really helpful!  Also, thanks so much for making this available, it's a life saver.
