### ISSUE TITLE
Having to use redis store for persistent data

### ISSUE THREAD

**Issue by dusual** [ozkatz/django-announce#3]
I want to use announce.js for an already written project in django and using mysql. I am using announce.js for the notifications. As I can see current implementation would require auth data to be in redis store. I was thinking as an enhancement to be able to use auth data from other db's and use redis store for notifications only. Would that make sense. I am not sure but I almost have some code written for this

**Comment by ozkatz** [comment]
You could create a fork that uses another storage engine for auth data, but this, of course, will not remove Redis as a dependency.
The so called "auth data" being used by announce.js is basically a disposable token. if it doesn't exist it will be created, so you don't _really_ have to have persistency enabled.
If Redis is wiped, current users connected will have their connections broken but on page refresh they will be reauthorized - a token will be regenerated for them by the client library.
